### ISSUE TITLE
Package collision with openmpi

### ISSUE THREAD

**Issue by carterbox** [conda-forge/openpmix-feedstock#1]
There is a potential package collision between this package and openmpi. Please work with the openmpi feedstock maintainers to mutually exclude each other. You may need to apply a repodata patch to prevent clobbering between already released packages.

https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fopenmpi-5.0.6-hd45feaf_100.conda

**Comment by minrk** [comment]
Good call. Since the main point of this feedstock is to unbundle the dependency from openmpi, when we do that we can add a repodata patch on past builds of openmpi with run_constrained to conflict with libpmix builds.
